// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class Book {
	/**
	 * 
	 */
	private String productName;

	public Book() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * 
	 */

	private List<String> genre;

	/**
	 * 
	 */
	private String author;
	/**
	 * 
	 */
	private String description;
	/**
	 * 
	 */
	private String imageFileName;
	/**
	 * 
	 */
	private int ISBN;
	/**
	 * 
	 */
	private int price;

	public String getProductName() {
		return productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getImageFileName() {
		return imageFileName;
	}

	public void setImageFileName(String imageFileName) {
		this.imageFileName = imageFileName;
	}

	public int getISBN() {
		return ISBN;
	}

	public void setISBN(int iSBN) {
		ISBN = iSBN;
	}

	public int getPrice() {
		return price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public Book(String productName, List<String> genre, String author, String description, String imageFileName,
			int iSBN, int price) {
		super();
		this.productName = productName;
		this.genre = genre;
		this.author = author;
		this.description = description;
		this.imageFileName = imageFileName;
		ISBN = iSBN;
		this.price = price;
	}

	public List<String> getGenre() {
		return genre;
	}

	public void setGenre(List<String> genre) {
		this.genre = genre;
	}

	/**
	 * 
	 */
	public void displayProduct() {

	}

	/**
	 * @param list3
	 * 
	 */
	List<Book> booklist1 = new ArrayList<>();

	public List<Book> getBookList() {
		return booklist1;
	}

	public static List<Book> bookList = new ArrayList<>();
	public static List<String> bookGenreList= new ArrayList<>();

	public static void initialzeBookData() {

		/*Book batmanBook = new Book("TheBatman", bookGenreList, "Adam West", "Story of a Batman in gotham-Year 1938",
				"TheBatmanPhoto", 101, 100);
		Book spiderManBook = new Book("SpiderMan", bookGenreList, "Stan Lee", "Story of a Spiderman-Year 1990",
				"TheSpiderManPhoto", 102, 50);

		Book book = new Book();
		book.setProductName("Doctor Strange");
		book.setGenre(bookGenreList);
		book.setAuthor("Adam West");
		book.setDescription("Story of Dr Strange in Nepal");
		book.setImageFileName("TheStrangePhoto");
		book.setISBN(101);
		book.setPrice(100);

		bookList.add(batmanBook);
		bookList.add(spiderManBook);
		bookList.add(book);*/
		
		Utils utils= new Utils();
		bookList=utils.getBookData();


	}

	public boolean verifyuniqueISBN(List<Book> booklist) {

		boolean flag = true;

		for (int i = 0; i < booklist.size(); i++) {
			if (i != booklist.size() - 1) {
				if (booklist.get(i).getISBN() == (booklist.get(i + 1).getISBN())) {
					flag = false;

				}

			}

		}
		return flag;

	}
}
