// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class OrderDetail {
	
	public OrderDetail(String productName, int orderId, int productId, int quantity, int unitCost, int subTotal,
			Book book) {
		super();
		this.productName = productName;
		this.orderId = orderId;
		this.productId = productId;
		this.quantity = quantity;
		this.unitCost = unitCost;
		this.subTotal = subTotal;
		this.book = book;
	}
	
	public OrderDetail() {
		
	}
	/**
	 * 
	 */
	private String productName;
	/**
	 * 
	 */
	private int orderId;
	/**
	 * 
	 */
	private int productId;
	/**
	 * 
	 */
	private int quantity;
	/**
	 * 
	 */
	private int unitCost;
	/**
	 * 
	 */
	private int subTotal;
	/**
	 * 
	 */
	public Book book;
	public String getProductName() {
		return productName;
	}
	public void setProductName(String productName) {
		this.productName = productName;
	}
	public int getOrderId() {
		return orderId;
	}
	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}
	public int getProductId() {
		return productId;
	}
	public void setProductId(int productId) {
		this.productId = productId;
	}
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	public int getUnitCost() {
		return unitCost;
	}
	public void setUnitCost(int unitCost) {
		this.unitCost = unitCost;
	}
	public int getSubTotal() {
		return subTotal;
	}
	public void setSubTotal(int subTotal) {
		this.subTotal = subTotal;
	}
}
