// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

/************************************************************/
/**
 * 
 */
public class ShippingInfo {
	/**
	 * 
	 */
	private String ShippingType;
	/**
	 * 
	 */
	private int shippingId;
	/**
	 * 
	 */
	private int shippingCost;
	/**
	 * 
	 */
	private int shippingRegionId;
	/**
	 * 
	 */
	public Order order;
	

	public ShippingInfo(String shippingType, int shippingId, int shippingCost, int shippingRegionId, Order order) {
		super();
		ShippingType = shippingType;
		this.shippingId = shippingId;
		this.shippingCost = shippingCost;
		this.shippingRegionId = shippingRegionId;
		this.order = order;
	}


	public String getShippingType() {
		return ShippingType;
	}


	public void setShippingType(String shippingType) {
		ShippingType = shippingType;
	}


	public int getShippingId() {
		return shippingId;
	}


	public void setShippingId(int shippingId) {
		this.shippingId = shippingId;
	}


	public int getShippingCost() {
		return shippingCost;
	}


	public void setShippingCost(int shippingCost) {
		this.shippingCost = shippingCost;
	}


	public int getShippingRegionId() {
		return shippingRegionId;
	}


	public void setShippingRegionId(int shippingRegionId) {
		this.shippingRegionId = shippingRegionId;
	}


	/**
	 * 
	 */
	public void updateShippingInfo() {
		
		System.out.println("Method To update shippinginfo for the order");
	}
}
