// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;

/************************************************************/
/**
 * 
 */
public class User {

	public User(String userId, String password, String loginStatus) {
		super();
		this.userId = userId;
		this.password = password;
		this.loginStatus = loginStatus;
	}

	public User(String userId, String password) {
		super();
		this.userId = userId;
		this.password = password;

	}

	public User() {

	}

	/**
	 * 
	 */
	private String userId;
	/**
	 * 
	 */
	private String password;
	/**
	 * 
	 */
	private String loginStatus;

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getLoginStatus() {
		return loginStatus;
	}

	public void setLoginStatus(String loginStatus) {
		this.loginStatus = loginStatus;
	}

	/**
	 * @param list
	 *            To do: remove hard coding and add a new method for verify password
	 *            length
	 * 
	 */
	public static List<String> userIdList = new ArrayList<String>();
	public static List<String> passwordList = new ArrayList<String>();
	public static List<Customer> userList = new ArrayList<>();

	/*
	 * public static void initializeData() {
	 * 
	 * 
	 * userIdList.add("sarfaraz94"); userIdList.add("fazil");
	 * 
	 * passwordList.add("Sarfu@94"); passwordList.add("Fazil@94");
	 * 
	 * Customer sarfaraz = new Customer("sarfaraz94", "abcd1234", "true",
	 * "1455 de massoinevve", "Sarfaraz", "sarfaraz94@xyz.com", "1234567890123456",
	 * "1455 de massoinevve", 1145145141, false);
	 * 
	 * Customer fazil = new Customer("fazil94", "12345678", "true",
	 * "1454 de massoinevve", "Fazil", "fazil94@xyz.com", "1234567890123456",
	 * "1454 de massoinevve", 1145145142, false); userList.add(sarfaraz);
	 * userList.add(fazil); }
	 */

	public boolean verifyUniqueUser(List<User> userList) {

		boolean flag = true;
		for (int i = 0; i < userList.size(); i++) {
			if (i != userList.size() - 1) {
				if (userList.get(i).getUserId().equals(userList.get(i + 1).getUserId())) {
					flag = false;

				}

				else
					return flag;
			}

		}
		return flag;

	}

	public boolean verifyPassword(List<User> userList) {
		for (User user : userList) {
			if (user.getPassword().length() < 8) {
				return false;
			}
		}
		return true;

	}

	public Customer verifyLogin(String userId, String password) {
		List<Customer> userListDB = Utils.getUserData();
		Customer customer = new Customer();
		boolean loginStatus = false;
		for (int i = 0; i < userListDB.size(); i++) {

			if (userId.equalsIgnoreCase(userListDB.get(i).getEmail())) {
				if (password.equals(userListDB.get(i).getPassword())) {
					System.out.println("Successful Login");
					customer = userListDB.get(i);
					break;
				} else {
					System.out.println(" Invalid Username or Password ");
					System.out.println("Please Rerun the system to start again.");
					System.exit(1);
				}

			} else {
				System.out.println(" Invalid Username or Password ");
				System.out.println("Please Rerun the system to start again.");
				System.exit(1);
			}

		}
		return customer;

	}
}
